version: "3.6"
services:
  server:
    build: ./server
    container_name: server
    restart: unless-stopped
  client:
    build: ./client
    container_name: client
    restart: unless-stopped
  proxy:
    image: caddy:2-alpine
    container_name: proxy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
      - client
    restart: unless-stopped

